// Code generated by "codegen ./internal/pkg/code"; DO NOT EDIT.

package code

import "github.com/che-kwas/iam-kit/errcoder"

// init register error codes defines in `github.com/marmotedu/errors`
func init() {
	errcoder.Register(ErrUserNotFound, 404, "User not found")
	errcoder.Register(ErrUserAlreadyExist, 400, "User already exist")
	errcoder.Register(ErrSecretNotFound, 404, "Secret not found")
	errcoder.Register(ErrReachMaxCount, 400, "Secret reach the max count")
	errcoder.Register(ErrPolicyNotFound, 404, "Policy not found")
}
