http:
  address: ${IAM_APISERVER_HTTP_ADDRESS} # 默认 0.0.0.0:8000
  mode: debug # release, debug, test，默认 release
  healthz: true # 是否开启健康检查, router: /healthz，默认 true
  metrics: false # 是否开启 metrics, router: /metrics，默认 false
  profiling: false # 是否开启性能分析, router: /debug/pprof，默认 false
  ping-timeout: 10s # http 服务启动后，自检超时时间，默认 10s

grpc:
  address: ${IAM_APISERVER_GRPC_ADDRESS} # 默认 0.0.0.0:8001
  max-msg-size: 4194304 # 4mb

jwt:
  key: dfVpOK8LZeJLZHYmHdb1VdyRrACKpqoo # 服务端密钥
  timeout: 24h # token 过期时间(小时)
  max-refresh: 24h # token 更新时间(小时)

mysql:
  host: ${IAM_MYSQL_HOST} # 默认 127.0.0.1:3306
  username: ${IAM_MYSQL_USERNAME}
  password: ${IAM_MYSQL_PASSWORD}
  database: ${IAM_MYSQL_DATABASE}
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info
